### ISSUE TITLE
Problem with color sensor 9694

### ISSUE THREAD

**Issue by MegaSova** [a10036gt/EV3-ColorAdvance-Block#1]
Hello, I have a problem with the 9694 nxt sensor. When you run it through your unit, it only lights up blue light, and the sensor registers only red. Is it possible to help with this, or at least an idea where the problem may lie in your block.

**Comment by MegaSova** [comment]
![photo_2022-09-27_17-47-55](https://user-images.githubusercontent.com/62509916/192559315-881d6706-337e-4522-b0e1-fb6fedb7fc0b.jpg)

**Comment by MegaSova** [comment]
![image](https://user-images.githubusercontent.com/62509916/192559408-91c5c359-ad5f-4956-acb7-5514e497c89b.png)

**Comment by a10036gt** [comment]
9694 nxt sensor is NXT Color, this block is for EV3 Color sensor, try out our NXT-Color-Block: https://github.com/a10036gt/EV3-NXT-Color-Block
